% This file is run in combustionSimulation.m
% Do not run this file as it is.
%
% This file contains derived properties for the physical design simulation of the Eyjafjallajökull hybrid rocket engine.
%
% DO NOT EDIT THIS FILE UNLESS YOU NEED TO ADD MORE DERIVED PROPERTIES. 
% ASSUMPTIONS AND INPUTS DO NOT GO IN THIS FILE

