% This file is run in nozzleSimulation.m
% Do not run this file as it is.
%
% This file contains derived properties for the nozzle simulation of the Eyjafjallajökull hybrid rocket engine.
%
% DO NOT EDIT THIS FILE UNLESS YOU NEED TO ADD MORE DERIVED PROPERTIES. 
% ASSUMPTIONS AND INPUTS DO NOT GO IN THIS FILE. 

opts.NozzleThroatDiameter = opts.NozzleThroatDiameterInCm / 100;
opts.NozzleExhaustDiameter = opts.NozzleExhaustDiameterInCm / 100;

opts.NozzleExhaustArea = (opts.NozzleExhaustDiameter / 2)^2 * pi;
opts.NozzleThroatArea = (opts.NozzleThroatDiameter / 2)^2 * pi;

opts.NozzleExpansionPressure = opts.NozzleExpansionPressureInAtmospheres * 101300;