% This file is run in nozzleSimulation.m
% Do not run this file as it is.
%
% This file contains derived properties for the nozzle simulation of the Eyjafjallajökull hybrid rocket engine.
%
% DO NOT EDIT THIS FILE UNLESS YOU NEED TO ADD MORE DERIVED PROPERTIES. 
% ASSUMPTIONS AND INPUTS DO NOT GO IN THIS FILE. 



p_cc = opts.NozzleDesignCombustionPressureInMpa*1e6;
p_e = opts.NozzleExpansionPressureInAtmospheres * 101325;
% throat

gamma = opts.NozzleDesignGamma; % this one needs to change in combustion as well
m_dot = opts.NozzleDesignMassFlow;

cstar = opts.NozzleDesignCStar;
A_t = (m_dot*cstar)/p_cc;
D_t = sqrt(4*A_t/pi);


%exit
A_e = A_t*( ((gamma-1)/2 * (2/(gamma+1))^((gamma+1)/(gamma-1))) / ((p_e/p_cc)^(2/gamma) * (1 - (p_e/p_cc)^((gamma-1)/gamma))) )^(1/2);
D_e = sqrt(4*A_e/pi);



%% oh no
opts.NozzleExpansionPressureInAtmospheres = p_e / 101325;
opts.NozzleThroatDiameterInCm = D_t/1e2;
opts.NozzleExhaustDiameterInCm = D_e/1e2; % The pressure which the nozzle expands exhaust to


opts.NozzleThroatDiameter = D_t;
opts.NozzleExhaustDiameter = D_e; % The pressure which the nozzle expands exhaust to


opts.NozzleExhaustArea = A_e;
opts.NozzleThroatArea = A_t;

opts.NozzleExpansionPressure = p_e;