% This file is run in flightSimulation.m
% Do not run this file as it is.
%
% This file contains derived properties for the combustion simulation of the Eyjafjallajökull hybrid rocket engine.
%
% DO NOT EDIT THIS FILE UNLESS YOU NEED TO ADD MORE DERIVED PROPERTIES. 
% ASSUMPTIONS AND INPUTS DO NOT GO IN THIS FILE

opts.nonPropulsionSystemMass = opts.parachuteMass + opts.electronicsMass + opts.bodyTubeMass + opts.payloadMass;

opts.engineDryMass = physicalDesignState.engineDryMass;
opts.propellantMass = physicalDesignState.propellantMass;
opts.oxidizerMass = physicalDesignState.oxidizerMass;
opts.fuelMass = physicalDesignState.fuelMass;

opts.dryMass = opts.nonPropulsionSystemMass + opts.engineDryMass;
opts.wetMass = opts.dryMass + opts.propellantMass;

opts.externalRadius = max(physicalDesignState.opts.ccRadius, physicalDesignState.opts.OxidizerTankRadius);